### ISSUE TITLE
Move fwd:cloudsec to separate bullet

### ISSUE THREAD

**Issue by 0xdabbad00** [brevityinmotion/straylight#1]
Happy to hear you've found my work useful! I would like a minor change to move fwd:cloudsec to a separate bullet though. I was one of the organizers, and Summit Route is my company, but fwd:cloudsec involved people from other companies as well (the other organizers all work for different companies), so I want to ensure the conference isn't viewed as being something that was run by my company as other folks deserve credit as well.

**Comment by brevityinmotion** [comment]
Fully agree and appreciate the feedback! Already looking forward to next year :). The team did tremendous! I added a conferences section and moved fwd:cloudsec to that section.
